services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: lukaswire/polls
    container_name: poll-app
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: poll-app-db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - poll-app-db:/var/lib/postgresql/data/

volumes:
  poll-app-db:
