version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: lukaswire/polls
    container_name: poll-bot
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: poll-bot-db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - poll-bot-db:/var/lib/postgresql/data/

volumes:
  poll-bot-db:
