services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: com.wire/poll-app
    container_name: poll-app
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - poll-app:/app/storage
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: poll-app-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - poll-app-db:/var/lib/postgresql/data/

volumes:
  poll-app-db:
  poll-app:
